[pytest]
addopts = -ra --tb=short --html=reports/report.html --self-contained-html --alluredir=allure-results
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
